title: <p align = "center"> Tejas Hankare </p>
logo: /assets/img/logo.png
description: I am a software developer with holistic knowledge of software development and design. I am also experienced in coordinating with stakeholders.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
